# Datenstrom Yellow extension settings

Extension: Parsedown
Version: 0.9.6
Description: Text formatting for humans.
Developer: Anna Svensson
Tag: feature
DownloadUrl: https://github.com/annaesvensson/yellow-parsedown/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/annaesvensson/yellow-parsedown
DocumentationLanguage: en, de, sv
Published: 2026-02-23 01:00:32
Status: experimental
system/workers/parsedown.php: parsedown.php, create, update
